name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jjunian10
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#a5ffc1
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#a5ffc1

      - name: Publish snake
        uses: github_user_name: jjulian10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
